apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vouch.fullname" . }}-couchdb-config
  labels:
    {{- include "vouch.labels" . | nindent 4 }}
data:
  {{- include "vouch.couchdb.extraIni" . | nindent 2 }}
