apiVersion: v2
name: vouch
description: A Helm chart for Vouch, a proxy for Apache CouchDB to offload token-based authentication.
type: application
version: 0.0.1
appVersion: "0.0.1"
keywords:
  - couchdb
  - jwt
  - proxy
  - security
  - sidecar
sources:
  - https://github.com/deep-rent/vouch
dependencies:
  - name: couchdb
    version: 4.6.3
    repository: https://apache.github.io/couchdb-helm
    condition: couchdb.enabled
maintainers:
  - name: deep-rent
    url: https://deep.rent
